### ISSUE TITLE
如果作者能够提供一份流程讲解就更棒了

### ISSUE THREAD

**Issue by refanbanzhang** [Kim09AI/react-juejin#3]
菜鸡一只，看起来有点理不清头绪，如果作者能够提供一份流程讲解就更棒了，哈哈

**Comment by Kim09AI** [comment]
近段时间应该没法写了，并且对你的水平也不清楚，假如有些库你还不熟悉的话，建议可以先学一下
- `rematch` 熟悉`redux`可以很快上手，不熟悉可以先学`redux`
- [`redux-connect`](https://github.com/makeomatic/redux-connect) 路由异步跳转，这里有一些比较简单的服务端渲染的例子 [点此](https://github.com/makeomatic/redux-connect/tree/master/examples)
- 以及服务端渲染cookie的共享，为什么要这么封装`axios`并放到`store`的`state`中，[点此](https://www.mmxiaowu.com/article/5b053d142fad053ed0369e99)，思路都是一样的，具体实现不一样而已

这样再看项目的话，应该就好理解一点了

**Comment by refanbanzhang** [comment]
谢谢！
