### ISSUE TITLE
非掘金站内文章无法显示

### ISSUE THREAD

**Issue by jibenziliao** [Kim09AI/react-juejin#6]
![image](https://user-images.githubusercontent.com/12134347/48236956-74c47d80-e3ff-11e8-9bd8-5365f1af1b8f.png)
非掘金站内文章进入的是另一个页面entry
比如：https://juejin.im/entry/5be4b2026fb9a049e23180e2
正常的文章是这样的：https://juejin.im/post/5be3d54cf265da611d6624d3
接口地址：https://entry-view-storage-api-ms.juejin.im/v1/getEntryView?src=web&entryId=5be4b2026fb9a049e23180e2
```
<div styleName="title-wrapper">
    <Link to={`/post/${getPostId(item.originalUrl)}`} styleName="title">{item.title}</Link>
</div>
```
这里不能直接跳转，需要做判断，根据entrylist里的type字段，非站内文章是article,普通文章是post
![image](https://user-images.githubusercontent.com/12134347/48237059-fddbb480-e3ff-11e8-8275-29072dcebd76.png)

**Comment by Kim09AI** [comment]
感谢指出来，不过我不打算再写关于业务部分的代码了，这个项目以后只会修改一下bug或做一些升级优化之类的
